load_stock_history_PCA <- function(stx_list.old) {
  Sys.setenv(TZ = "UTC")
  adjustment <- TRUE
  start_date <- "2006-01-01" 
  end_date <- "2010-01-01"
  getSymbols(Symbols = com.env$stx_list,
           env=data.env,
           src = "yahoo", 
           index.class = "POSIXct",
           from = start_date, 
           to = end_date, 
           adjust = adjustment)
  #calc_adjusted_HLOJRlD(com.env$stx_list)
  
  return(com.env$stx_list)
}
stock_list_PCA <- function() {
  symbols <- c(
    "A",
    "AA",
    "AAL",
    "AAP",
    "AAPL",
    #"ABBV",
    "ABC",
    #"ABI",
    "ABK",
    "ABT",
    #"ACAS",
    #"ACE",
    "ACN",
    #"ACS",
    "ADBE",
    "ADI",
    "ADM",
    "ADP",
    "ADS",
    "ADSK",
    #"ADT",
    "AEE",
    "AEP",
    "AES",
    "AET",
    "AFL",
    "AGN",
    #"AGN (Old)",
    "AIG",
    "AIV",
    "AIZ",
    "AKAM",
    "AKS",
    "ALL",
    #"ALLE",
    #"ALTR",
    "ALXN",
    "AMAT",
    "AMD",
    "AME",
    "AMG",
    "AMGN",
    "AMP",
    "AMT",
    "AMZN",
    "AN",
    "ANF",
    #"ANR",
    "ANTM",
    "AON",
    "APA",
    "APC",
    "APD",
    "APH",
    #"APOL",
    #"ARG",
    "ASH",
    "ATI",
    "ATVI",
    #"AW",
    "AVB",
    #"AVGO",
    "AVP",
    "AVY",
    "AXP",
    #"AYE",
    "AZO",
    "BA",
    "BAC",
    "BAX",
    "BBBY",
    "BBT",
    "BBY",
    "BC",
    "BCR",
    #"BDK",
    "BDX",
    #"BEAM",
    "BEN",
    #"BF.B",
    "BHI",
    "BIG",
    "BIIB",
    #"BJS",
    "BK",
    "BLK",
    "BLL",
    #"BMC",
    "BMS",
    "BMY",
    #"BNI",
    #"BRCM",
    #"BRK.B",
    #"BRL",
    #"BSC",
    "BSX",
    #"BTU",
    #"BUD",
    "BWA",
    #"BXLT",
    "BXP",
    "C",
    "CA",
    "CAG",
    "CAH",
    #"CAM",
    "CAT",
    "CB",
    "CBE",
    "CBG",
    #"CBH",
    "CBS",
    #"CC",
    "CCE",
    "CCI",
    "CCL",
    #"CEG",
    "CELG",
    #"CEPH",
    "CERN",
    "CF",
    #"CFC",
    #"CFN",
    "CHD",
    "CHK",
    "CHRW",
    "CI",
    "CIEN",
    "CINF",
    #"CIT",
    "CL",
    "CLF",
    "CLX",
    "CMA",
    "CMCSA",
    "CME",
    "CMG",
    "CMI",
    "CMS",
    "CNP",
    "CNX",
    "COF",
    "COG",
    "COH",
    "COL",
    "COP",
    "COST",
    #"COV",
    "CPB",
    #"CPGX",
    #"CPWR",
    "CRM",
    #"CSC",
    "CSCO",
    #"CSRA",
    "CSX",
    "CTAS",
    "CTL",
    "CTSH",
    #"CTX",
    "CTXS",
    #"CVC",
    "CVG",
    #"CVH",
    "CVS",
    "CVX",
    #"CZR",
    "D",
    "DAL",
    "DD",
    "DDR",
    "DDS",
    "DE",
    #"DELL",
    "DF",
    "DFS",
    "DG",
    "DGX",
    "DHI",
    "DHR",
    "DIS",
    "DISCA",
    "DISCK",
    #"DLPH",
    "DLTR",
    "DNB",
    "DNR",
    "DO",
    "DOV",
    "DOW",
    "DPS",
    "DRI",
    "DTE",
    #"DTV",
    "DUK",
    "DV",
    "DVA",
    "DVN",
    #"DYN",
    "EA",
    "EBAY",
    "ECL",
    "ED",
    #"EDS",
    "EFX",
    "EIX",
    #"EK",
    "EL",
    #"EMC",
    "EMN",
    "EMR",
    "ENDP",
    "EOG",
    #"EP",
    #"EQ",
    "EQIX",
    "EQR",
    "EQT",
    "ES",
    "ESRX",
    "ESS",
    "ESV",
    "ETFC",
    "ETN",
    "ETR",
    "EW",
    "EXC",
    "EXPD",
    "EXPE",
    "F",
    "FAST",
    #"FB",
    "FCX",
    #"FDO",
    "FDX",
    "FE",
    "FFIV",
    "FHN",
    "FII",
    "FIS",
    "FISV",
    "FITB",
    "FLIR",
    "FLR",
    "FLS",
    "FMC",
    #"FNM",
    "FOSL",
    "FOX",
    "FOXA",
    #"FRE",
    #"FRX",
    "FSLR",
    "FTI",
    "FTR",
    #"GAS",
    "GCI",
    "GD",
    "GE",
    #"GENZ",
    "GGP",
    "GHC",
    "GILD",
    "GIS",
    "GLW",
    #"GM",
    #"GMCR",
    "GME",
    "GNW",
    "GOOG",
    "GOOGL",
    "GPC",
    "GPS",
    #"GR",
    "GRMN",
    "GS",
    "GT",
    "GWW",
    "HAL",
    #"HAR",
    "HAS",
    "HBAN",
    "HBI",
    #"HCA",
    #"HCBK",
    "HCN",
    #"HCP",
    "HD",
    "HES",
    "HIG",
    "HNZ",
    "HOG",
    "HON",
    #"HOT",
    "HP",
    #"HPC",
    #"HPE",
    "HPQ",
    "HRB",
    "HRL",
    "HRS",
    #"HSH",
    "HSIC",
    #"HSP",
    "HST",
    "HSY",
    "HUM",
    #"IACI",
    "IBM",
    "ICE",
    "IFF",
    "IGT",
    "IHRT",
    "ILMN",
    #"IMS",
    "INTC",
    "INTU",
    "IP",
    "IPG",
    "IR",
    "IRM",
    "ISRG",
    "ITT",
    "ITW",
    "IVZ",
    #"JAVA",
    "JBHT",
    "JBL",
    "JCI",
    "JCP",
    "JEC",
    "JNJ",
    "JNPR",
    "JNS",
    #"JNY",
    #"JOY",
    "JPM",
    "JWN",
    "K",
    "KATE",
    "KBH",
    "KEY",
    #"KG",
    #"KHC",
    "KIM",
    "KLAC",
    "KMB",
    #"KMI",
    "KMX",
    "KO",
    #"KORS",
    "KR",
    "KSS",
    "KSU",
    "L",
    "LB",
    "LDOS",
    "LEG",
    #"LEH",
    "LEN",
    "LH",
    #"LIFE",
    "LLL",
    #"LLTC",
    "LLY",
    "LM",
    "LMT",
    "LNC",
    #"LO",
    "LOW",
    "LRCX",
    "LSI",
    "LUK",
    "LUV",
    "LVLT",
    #"LXK",
    #"LYB",
    "M",
    "MA",
    "MAC",
    "MAR",
    "MAS",
    "MAT",
    "MBI",
    "MCD",
    "MCHP",
    "MCK",
    "MCO",
    "MDLZ",
    "MDP",
    "MDT",
    #"MEE",
    #"MER",
    "MET",
    #"MFE",
    #"MHFI",
    "MHK",
    #"MHS",
    #"MI",
    #"MIL",
    "MJN",
    "MKC",
    "MLM",
    "MMC",
    #"MMI",
    "MMM",
    #"MNK",
    "MNST",
    "MO",
    "MOLX",
    "MON",
    "MOS",
    #"MPC",
    "MRK",
    "MRO",
    "MS",
    "MSFT",
    "MSI",
    "MTB",
    "MTG",
    "MTW",
    "MU",
    "MUR",
    #"MWV",
    #"MWW",
    "MYL",
    #"NAVI",
    "NBL",
    "NBR",
    #"NCC",
    "NDAQ",
    "NE",
    "NEE",
    "NEM",
    "NFLX",
    "NFX",
    "NI",
    "NKE",
    #"NLSN",
    "NOC",
    "NOV",
    #"NOVL",
    "NRG",
    "NSC",
    #"NSM",
    "NTAP",
    "NTRS",
    "NUE",
    "NVDA",
    "NWL",
    #"NVLS",
    #"NWS",
    #"NWSA",
    "NYT",
    "NYX",
    "O",
    "ODP",
    "OI",
    "OKE",
    "OMC",
    "OMX",
    "ORCL",
    "ORLY",
    "OXY",
    "PAYX",
    "PBCT",
    #"PBG",
    "PBI",
    "PCAR",
    "PCG",
    #"PCL",
    "PCLN",
    #"PCP",
    #"PCS",
    "PDCO",
    "PEG",
    "PEP",
    #"PETM",
    "PFE",
    "PFG",
    "PG",
    #"PGN",
    "PGR",
    "PH",
    "PHM",
    "PKI",
    "PLD",
    #"PLL",
    "PM",
    "PNC",
    "PNR",
    "PNW",
    #"POM",
    "PPG",
    "PPL",
    "PRGO",
    "PRU",
    "PSA",
    #"PSX",
    #"PTV",
    "PVH",
    "PWR",
    "PX",
    "PXD",
    #"PYPL",
    #"Q",
    "QCOM",
    #"QEP",
    #"QLGC",
    #"QRVO",
    "R",
    "RAI",
    "RCL",
    "RDC",
    "REGN",
    "RF",
    "RHI",
    "RHT",
    "RIG",
    "RL",
    #"ROH",
    "ROK",
    "ROP",
    "ROST",
    "RRC",
    "RRD",
    "RSG",
    #"RSH",
    "RTN",
    "S",
    #"SAF",
    "SBUX",
    "SCG",
    "SCHW",
    #"SE",
    "SEE",
    #"SGP",
    "SHLD",
    "SHW",
    #"SIAL",
    "SIG",
    #"SII",
    "SJM",
    "SLB",
    "SLG",
    "SLM",
    "SNA",
    #"SNDK",
    "SNI",
    "SO",
    #"SOV",
    "SPG",
    "SPLS",
    "SRCL",
    "SRE",
    "SSP",
    "STI",
    #"STJ",
    #"STR",
    "STT",
    "STX",
    "STZ",
    "SUN",
    #"SUNE",
    "SWK",
    "SWKS",
    "SWN",
    "SVU",
    #"SWY",
    #"SYF",
    "SYK",
    "SYMC",
    "SYY",
    "T",
    "TAP",
    "TDC",
    #"TE",
    #"TEG",
    "TEL",
    "TER",
    "TEX",
    "TGT",
    "THC",
    "TIE",
    "TIF",
    "TJX",
    "TLAB",
    "TMK",
    "TMO",
    #"TRIP",
    "TROW",
    "TRV",
    "TSCO",
    "TSN",
    "TSO",
    "TSS",
    #"TT",
    #"TWC",
    "TWX",
    "TXN",
    "TXT",
    #"TYC",
    #"UA",
    "UAL",
    "UHS",
    "UIS",
    "UNH",
    "UNM",
    "UNP",
    "UPS",
    "URBN",
    "URI",
    "USB",
    #"UST",
    "UTX",
    "V",
    #"WAMUQ",
    "VAR",
    "WAT",
    #"WB",
    "WBA",
    "WDC",
    "WEC",
    "WEN",
    "VFC",
    "WFC",
    "WFM",
    "WFT",
    "WHR",
    "VIAB",
    "VIAV",
    "WIN",
    "VLO",
    "WM",
    "WMB",
    "VMC",
    "WMT",
    "VNO",
    #"WPX",
    "VRSK",
    "VRSN",
    "VRTX",
    "VTR",
    "VZ",
    "WU",
    #"WWY",
    "WY",
    #"WYE",
    "WYN",
    "WYNN",
    "X",
    "XEC",
    "XEL",
    "XL",
    "XLNX",
    "XOM",
    "XRAY",
    "XRX",
    #"XTO",
    #"XYL",
    "YHOO",
    "YUM",
    "ZBH",
    "ZION"
    #"ZTS"
  )
  com.env$stx_list <- symbols
}

#doesn't handle coln==0
calc_adjret_PCA <- function(ve.xts,field,first_pass=FALSE) {
  #print(paste("ve.xts",ve.xts,"coln",coln,"field",field))
  ticker <- sub("var.env$","",ve.xts,fixed=TRUE)
  de.xts <- paste("data.env$",ticker,"$",ticker,field,sep="")
  cmd_string <- paste(ve.xts," <- (stats::lag(",de.xts,",-1)-",de.xts,")/",de.xts,sep="")
  #print(cmd_string)
  eval(parse(text=cmd_string))
}
calc_wrapper <- function(stx_list){
  PCA_matrix <- NULL
  for (ticker in stx_list){
    ve.xts <- paste0("var.env$",ticker)
    calc_adjret_PCA(ve.xts, ".Adjusted")
    command_string <- paste0("PCA_matrix <- cbind(PCA_matrix,",ve.xts,")")
    eval(parse(text=command_string))
  }
  return (PCA_matrix)
}
load_packages <- function() {
  library(lpSolveAPI)
  library(quantmod)
  library(dplyr)
  library(forecast)
  library(leaps)
  library(fmsb)
  library(MASS)
}
load_packages()
data.env <<- new.env(parent=globalenv())
var.env <<- new.env(parent=globalenv())
rnd.env <<- new.env(parent=globalenv())
com.env <<- new.env(parent=globalenv())
if (!exists("stx_list.loaded")) stx_list.loaded <- NULL 
stock_list_PCA()   
stx_list.loaded <- load_stock_history_PCA(stx_list.loaded)  
PCA_matrix <- calc_wrapper(stx_list.loaded)
PCA_matrix <- PCA_matrix[,colSums(is.na(PCA_matrix))==1]
PCA_matrix <- na.omit(PCA_matrix)

#Finds top 50 correlated stocks and runs stepwise regression for each stock in PCA_matrix
Correlated_stocks <- function(PCA_matrix){
  PCA_correlation = cor(PCA_matrix)
  num_stocks = 50
  stocks = colnames(PCA_correlation)
  results = list()
  Rsquared = list()
  
  for (j in 1:491){
  
    stock = sort(PCA_correlation[,j], decreasing=TRUE)[1:num_stocks]
    corr_stock = names(stock)
    
    string = ""
    for (i in 2:49){
      string = paste0(string,corr_stock[i],"+")
    }
    string = paste0(string,corr_stock[50])
    
    command_string <- paste0("fit <- lm(",stocks[j],"~0+",string,",data=PCA_matrix)")
    eval(parse(text=command_string))
    step <- stepAIC(fit, direction="both")
    result = step$coefficients
    results[[j]] = result
    names(results)[j] <- stocks[j]
    Rsquared[[j]] = summary(step)$adj.r.squared
    names(Rsquared)[j] <- stocks[j]
  }
  return(results) 
}
Unconstrained_results <- Correlated_stocks(PCA_matrix)

lower_bound = as.list(rep(0, 50))

stock = sort(PCA_correlation[,1], decreasing=TRUE)[1:num_stocks]
corr_stock = names(stock)
string = ""
for (i in 2:49){
  string = paste0(string,corr_stock[i],"+")
}
string = paste0(string,corr_stock[50])
PCA_matrix.df <- as.data.frame(PCA_matrix)
command_string <- paste0("fit <- nls(",stocks[1],"~0+",string,",data=PCA_matrix.df,start=lower_bound,lower=lower_bound)")
eval(parse(text=command_string))

#PCA analysis
pr.out=prcomp(PCA_matrix[104:354,], center=TRUE, scale = TRUE)

pr.out$center
pr.out$scale
rot = pr.out$rotation

biplot(pr.out, scale=0)
pr.var=pr.out$sdev^2
pve=pr.var/sum(pr.var)
plot(pve, xlab="Principal component", ylab="Proportion of Variance Explained", ylim=c(0,1), type='b')
plot(cumsum(pve), xlab="Principal Component", ylab="Cumulative Proportion of Variation Explained", ylim=c(0,1),type='b')

#june 2006 - May 2007 PCA analysis
pr.out=prcomp(PCA_matrix[104:354,], center=TRUE, scale = TRUE)
top10 = list()
bottom10 = list()
for (i in 2:6){
  sorted = sort(rot[,i], decreasing = TRUE)
  top10[[i-1]] = names(sorted[1:10])
  bottom10[[i-1]] = names(tail(sorted, 10))
}
names(top10) <- names(rot[1,][2:6])
names(bottom10) <- names(rot[1,][2:6])
